### ISSUE TITLE
Any idea how to use this project as an api for Scriptable?

### ISSUE THREAD

**Issue by wickenico** [19201080/risikogebiete-api#2]
Hi,

I was looking for an api for the risk areas defined by German rki.
My plan is to use this for a Scriptable Widget which would be written in JavaScript.

Is it possible to use this project with JavaScript or could you give me any tips or ideas? 

Thanks a lot!

**Comment by 19201080** [comment]
Hi, thanks for the interest! I don't know about scriptable widgets, but it's definitely doable in javascript. I would recommend looking into the [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) as well as solutions for parsing [csv](https://www.npmjs.com/package/csv) or [json](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse).

That way you could:
- fetch the [data.csv](https://github.com/19201080/risikogebiete-api/blob/main/data.csv) or [data.json](https://github.com/19201080/risikogebiete-api/blob/main/data.json) file
- parse the result
- use the data in your application

As a side note, the RKI introduced a breaking change in their format some time ago, so i need to solve the issue #1 to make the api work with their current reports (if you look into the data you'll see the breaking change on the report of may 12).
